"""
Seed data for Egyptian pharmacy products.
Contains a comprehensive list of real medicines commonly found in Egyptian pharmacies.
"""

PRODUCTS = [
    # ==========================================
    # 1. مسكنات وخوافض حرارة
    # ==========================================
    {
        'name': 'Panadol Extra',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن للآلام وخافض للحرارة يحتوي على باراسيتامول وكافيين',
        'price': '24.00',
        'stock': 150,
        'barcode': '6221060001012',
        'requires_prescription': False,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-06-15',
    },
    {
        'name': 'Brufen 400',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن ومضاد للالتهابات يحتوي على ايبوبروفين 400 مجم',
        'price': '30.00',
        'stock': 120,
        'barcode': '6221060001029',
        'requires_prescription': False,
        'manufacturer': 'أبوت',
        'expiry_date': '2027-09-20',
    },
    {
        'name': 'Cataflam 50',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن قوي ومضاد للالتهابات يحتوي على ديكلوفيناك بوتاسيوم',
        'price': '36.00',
        'stock': 100,
        'barcode': '6221060001036',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-12-01',
    },
    {
        'name': 'Ketofan',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن ومضاد للالتهابات يحتوي على كيتوبروفين',
        'price': '21.00',
        'stock': 80,
        'barcode': '6221060001043',
        'requires_prescription': False,
        'manufacturer': 'آمون للأدوية',
        'expiry_date': '2028-01-10',
    },
    {
        'name': 'Paracetamol 500',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن للآلام وخافض للحرارة - باراسيتامول 500 مجم',
        'price': '9.00',
        'stock': 200,
        'barcode': '6221060001050',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-08-25',
    },
    {
        'name': 'Aspirin 300',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن ومضاد للالتهابات ومانع لتجلط الدم',
        'price': '12.00',
        'stock': 90,
        'barcode': '6221060001067',
        'requires_prescription': False,
        'manufacturer': 'باير',
        'expiry_date': '2028-03-15',
    },
    {
        'name': 'Voltaren 50',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن قوي ومضاد للالتهابات يحتوي على ديكلوفيناك صوديوم',
        'price': '33.00',
        'stock': 75,
        'barcode': '6221060001074',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-11-30',
    },

    # ==========================================
    # 2. مضادات حيوية
    # ==========================================
    {
        'name': 'Augmentin 1g',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي واسع المجال يحتوي على أموكسيسيلين وحمض كلافولانيك',
        'price': '93.00',
        'stock': 60,
        'barcode': '6221060002019',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-05-20',
    },
    {
        'name': 'Amoxil 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي يحتوي على أموكسيسيلين لعلاج العدوى البكتيرية',
        'price': '30.00',
        'stock': 85,
        'barcode': '6221060002026',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-07-15',
    },
    {
        'name': 'Flumox 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي واسع المجال يحتوي على أموكسيسيلين وفلوكلوكساسيلين',
        'price': '42.00',
        'stock': 70,
        'barcode': '6221060002033',
        'requires_prescription': True,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-10-05',
    },
    {
        'name': 'Cefotax 1g',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي من مجموعة السيفالوسبورين للحقن',
        'price': '18.00',
        'stock': 50,
        'barcode': '6221060002040',
        'requires_prescription': True,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2028-02-28',
    },
    {
        'name': 'Cipro 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي من مجموعة الفلوروكينولون لعلاج العدوى البكتيرية',
        'price': '45.00',
        'stock': 55,
        'barcode': '6221060002057',
        'requires_prescription': True,
        'manufacturer': 'باير',
        'expiry_date': '2027-08-10',
    },
    {
        'name': 'Zithromax 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي يحتوي على أزيثرومايسين لعلاج عدوى الجهاز التنفسي',
        'price': '67.00',
        'stock': 45,
        'barcode': '6221060002064',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-01-20',
    },
    {
        'name': 'Flagyl 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد للبكتيريا والطفيليات يحتوي على ميترونيدازول',
        'price': '15.00',
        'stock': 100,
        'barcode': '6221060002071',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2027-06-30',
    },
    {
        'name': 'Klacid 500',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي يحتوي على كلاريثرومايسين لعلاج عدوى الجهاز التنفسي',
        'price': '78.00',
        'stock': 40,
        'barcode': '6221060002088',
        'requires_prescription': True,
        'manufacturer': 'أبوت',
        'expiry_date': '2027-11-15',
    },

    # ==========================================
    # 3. أدوية القلب والأوعية الدموية
    # ==========================================
    {
        'name': 'Concor 5',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم وقصور القلب - بيسوبرولول',
        'price': '52.00',
        'stock': 65,
        'barcode': '6221060003016',
        'requires_prescription': True,
        'manufacturer': 'ميرك',
        'expiry_date': '2028-04-10',
    },
    {
        'name': 'Plavix 75',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'مانع لتجلط الدم يحتوي على كلوبيدوجريل',
        'price': '105.00',
        'stock': 50,
        'barcode': '6221060003023',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2027-09-25',
    },
    {
        'name': 'Aspocid 75',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'أسبرين بجرعة منخفضة لمنع تجلط الدم وحماية القلب',
        'price': '10.50',
        'stock': 180,
        'barcode': '6221060003030',
        'requires_prescription': False,
        'manufacturer': 'كيميكال إندستريز للتنمية (سيد)',
        'expiry_date': '2028-02-14',
    },
    {
        'name': 'Isoptin 80',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'يستخدم لعلاج اضطرابات نظم القلب والذبحة الصدرية - فيراباميل',
        'price': '25.00',
        'stock': 40,
        'barcode': '6221060003047',
        'requires_prescription': True,
        'manufacturer': 'أبوت',
        'expiry_date': '2027-12-20',
    },
    {
        'name': 'Lipitor 20',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'يستخدم لخفض مستوى الكوليسترول في الدم - أتورفاستاتين',
        'price': '90.00',
        'stock': 55,
        'barcode': '6221060003054',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-05-01',
    },

    # ==========================================
    # 4. أدوية السكر
    # ==========================================
    {
        'name': 'Glucophage 1000',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج مرض السكر من النوع الثاني - ميتفورمين',
        'price': '30.00',
        'stock': 90,
        'barcode': '6221060004013',
        'requires_prescription': True,
        'manufacturer': 'ميرك',
        'expiry_date': '2028-03-10',
    },
    {
        'name': 'Amaryl 2',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج السكر من النوع الثاني - جليميبرايد',
        'price': '45.00',
        'stock': 70,
        'barcode': '6221060004020',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2027-11-25',
    },
    {
        'name': 'Diamicron MR 60',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج السكر من النوع الثاني - جليكلازيد',
        'price': '72.00',
        'stock': 55,
        'barcode': '6221060004037',
        'requires_prescription': True,
        'manufacturer': 'سيرفييه',
        'expiry_date': '2028-01-05',
    },
    {
        'name': 'Januvia 100',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج السكر من النوع الثاني - سيتاجليبتين',
        'price': '210.00',
        'stock': 35,
        'barcode': '6221060004044',
        'requires_prescription': True,
        'manufacturer': 'ميرك شارب آند دوم',
        'expiry_date': '2027-08-18',
    },
    {
        'name': 'Lantus Solostar',
        'category': 'أدوية السكر',
        'description': 'أنسولين طويل المفعول لعلاج مرض السكر - إنسولين جلارجين',
        'price': '285.00',
        'stock': 25,
        'barcode': '6221060004051',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2027-06-01',
    },
    {
        'name': 'Mixtard 30',
        'category': 'أدوية السكر',
        'description': 'أنسولين مخلوط لعلاج مرض السكر',
        'price': '78.00',
        'stock': 30,
        'barcode': '6221060004068',
        'requires_prescription': True,
        'manufacturer': 'نوفو نورديسك',
        'expiry_date': '2027-09-12',
    },

    # ==========================================
    # 5. أدوية الضغط
    # ==========================================
    {
        'name': 'Tritace 5',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - راميبريل',
        'price': '48.00',
        'stock': 60,
        'barcode': '6221060005014',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2028-02-20',
    },
    {
        'name': 'Plendil 5',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - فيلوديبين',
        'price': '42.00',
        'stock': 50,
        'barcode': '6221060005021',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2027-07-30',
    },
    {
        'name': 'Exforge 5/160',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - أملوديبين وفالسارتان',
        'price': '120.00',
        'stock': 40,
        'barcode': '6221060005038',
        'requires_prescription': True,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2028-04-15',
    },
    {
        'name': 'Co-Diovan 160/12.5',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - فالسارتان وهيدروكلوروثيازيد',
        'price': '95.00',
        'stock': 45,
        'barcode': '6221060005045',
        'requires_prescription': True,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-10-22',
    },
    {
        'name': 'Concor 2.5',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - بيسوبرولول 2.5 مجم',
        'price': '38.00',
        'stock': 70,
        'barcode': '6221060005052',
        'requires_prescription': True,
        'manufacturer': 'ميرك',
        'expiry_date': '2028-01-30',
    },
    {
        'name': 'Atacand 16',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم - كانديسارتان',
        'price': '85.00',
        'stock': 35,
        'barcode': '6221060005069',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2027-12-10',
    },

    # ==========================================
    # 6. فيتامينات ومكملات غذائية
    # ==========================================
    {
        'name': 'Centrum Silver',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي متعدد الفيتامينات والمعادن للكبار',
        'price': '195.00',
        'stock': 80,
        'barcode': '6221060006011',
        'requires_prescription': False,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-06-15',
    },
    {
        'name': 'Pharmaton',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي لزيادة النشاط والطاقة يحتوي على جينسنج',
        'price': '120.00',
        'stock': 65,
        'barcode': '6221060006028',
        'requires_prescription': False,
        'manufacturer': 'بورنغر إنغلهايم',
        'expiry_date': '2027-10-20',
    },
    {
        'name': 'Omega 3 Plus',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي يحتوي على أحماض أوميغا 3 الدهنية لصحة القلب',
        'price': '60.00',
        'stock': 90,
        'barcode': '6221060006035',
        'requires_prescription': False,
        'manufacturer': 'سيديكو',
        'expiry_date': '2028-03-01',
    },
    {
        'name': 'Caltrate 600+D',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي يحتوي على كالسيوم وفيتامين د لصحة العظام',
        'price': '75.00',
        'stock': 70,
        'barcode': '6221060006042',
        'requires_prescription': False,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-05-10',
    },
    {
        'name': 'Vidrop',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'نقط فيتامين د للأطفال والكبار لتقوية العظام',
        'price': '30.00',
        'stock': 120,
        'barcode': '6221060006059',
        'requires_prescription': False,
        'manufacturer': 'ميديكال يونيون للأدوية (MUP)',
        'expiry_date': '2027-11-05',
    },
    {
        'name': 'Zinc Forte',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي يحتوي على زنك لتقوية المناعة',
        'price': '42.00',
        'stock': 100,
        'barcode': '6221060006066',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2028-01-25',
    },
    {
        'name': 'Feroglobin B12',
        'category': 'فيتامينات ومكملات غذائية',
        'description': 'مكمل غذائي يحتوي على حديد وفيتامين ب12 وحمض فوليك',
        'price': '135.00',
        'stock': 55,
        'barcode': '6221060006073',
        'requires_prescription': False,
        'manufacturer': 'فيتابيوتيكس',
        'expiry_date': '2027-09-18',
    },

    # ==========================================
    # 7. أدوية الجهاز الهضمي
    # ==========================================
    {
        'name': 'Antinal 200',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'مطهر معوي لعلاج الإسهال والتهابات الأمعاء - نيفوروكسازيد',
        'price': '21.00',
        'stock': 140,
        'barcode': '6221060007018',
        'requires_prescription': False,
        'manufacturer': 'آمون للأدوية',
        'expiry_date': '2027-08-30',
    },
    {
        'name': 'Nexium 40',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'يستخدم لعلاج الحموضة وقرحة المعدة - إيزوميبرازول',
        'price': '84.00',
        'stock': 60,
        'barcode': '6221060007025',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2028-02-10',
    },
    {
        'name': 'Motilium 10',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'يستخدم لعلاج الغثيان والقيء وعسر الهضم - دومبيريدون',
        'price': '27.00',
        'stock': 85,
        'barcode': '6221060007032',
        'requires_prescription': False,
        'manufacturer': 'جانسن',
        'expiry_date': '2027-10-15',
    },
    {
        'name': 'Duspatalin 200',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'يستخدم لعلاج تقلصات القولون العصبي - ميبيفيرين',
        'price': '54.00',
        'stock': 70,
        'barcode': '6221060007049',
        'requires_prescription': False,
        'manufacturer': 'أبوت',
        'expiry_date': '2028-04-20',
    },
    {
        'name': 'Lactulose',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'ملين لعلاج الإمساك يعمل على زيادة حركة الأمعاء',
        'price': '18.00',
        'stock': 95,
        'barcode': '6221060007056',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-07-22',
    },
    {
        'name': 'Gaviscon Advance',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'يستخدم لعلاج الحموضة والارتجاع المريئي',
        'price': '66.00',
        'stock': 75,
        'barcode': '6221060007063',
        'requires_prescription': False,
        'manufacturer': 'ريكيت بنكيزر',
        'expiry_date': '2028-01-15',
    },
    {
        'name': 'Controloc 40',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'يستخدم لعلاج قرحة المعدة والحموضة - بانتوبرازول',
        'price': '72.00',
        'stock': 50,
        'barcode': '6221060007070',
        'requires_prescription': True,
        'manufacturer': 'نيكوميد',
        'expiry_date': '2027-12-28',
    },

    # ==========================================
    # 8. أدوية البرد والإنفلونزا
    # ==========================================
    {
        'name': 'Comtrex',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'يستخدم لعلاج أعراض البرد والإنفلونزا والصداع',
        'price': '24.00',
        'stock': 130,
        'barcode': '6221060008015',
        'requires_prescription': False,
        'manufacturer': 'بريستول مايرز سكويب',
        'expiry_date': '2027-05-15',
    },
    {
        'name': 'Congestal',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'يستخدم لعلاج أعراض البرد والاحتقان والرشح',
        'price': '18.00',
        'stock': 150,
        'barcode': '6221060008022',
        'requires_prescription': False,
        'manufacturer': 'آمون للأدوية',
        'expiry_date': '2027-09-10',
    },
    {
        'name': 'Flurest',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'أقراص لعلاج نزلات البرد والإنفلونزا',
        'price': '15.00',
        'stock': 120,
        'barcode': '6221060008039',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-11-01',
    },
    {
        'name': '123 Cold & Flu',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'أقراص لعلاج أعراض البرد والإنفلونزا والحمى',
        'price': '12.00',
        'stock': 160,
        'barcode': '6221060008046',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2028-03-20',
    },
    {
        'name': 'Otrivin Spray',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'بخاخ أنف لعلاج الاحتقان وانسداد الأنف - زايلوميتازولين',
        'price': '27.00',
        'stock': 80,
        'barcode': '6221060008053',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-08-05',
    },
    {
        'name': 'Strepsils',
        'category': 'أدوية البرد والإنفلونزا',
        'description': 'أقراص استحلاب لعلاج التهاب الحلق والبلعوم',
        'price': '33.00',
        'stock': 100,
        'barcode': '6221060008060',
        'requires_prescription': False,
        'manufacturer': 'ريكيت بنكيزر',
        'expiry_date': '2028-01-12',
    },

    # ==========================================
    # 9. أدوية جلدية
    # ==========================================
    {
        'name': 'Fucicort Cream',
        'category': 'أدوية جلدية',
        'description': 'كريم مضاد للبكتيريا والالتهابات الجلدية - فيوسيديك أسيد وبيتاميثازون',
        'price': '45.00',
        'stock': 60,
        'barcode': '6221060009012',
        'requires_prescription': True,
        'manufacturer': 'ليو فارما',
        'expiry_date': '2027-07-25',
    },
    {
        'name': 'Betadine Solution',
        'category': 'أدوية جلدية',
        'description': 'محلول مطهر للجروح والحروق - بوفيدون أيودين',
        'price': '22.00',
        'stock': 110,
        'barcode': '6221060009029',
        'requires_prescription': False,
        'manufacturer': 'النيل للأدوية',
        'expiry_date': '2028-05-10',
    },
    {
        'name': 'Fucidin Cream',
        'category': 'أدوية جلدية',
        'description': 'كريم مضاد حيوي موضعي لعلاج العدوى البكتيرية الجلدية',
        'price': '38.00',
        'stock': 70,
        'barcode': '6221060009036',
        'requires_prescription': False,
        'manufacturer': 'ليو فارما',
        'expiry_date': '2027-10-08',
    },
    {
        'name': 'Daktarin Cream',
        'category': 'أدوية جلدية',
        'description': 'كريم مضاد للفطريات لعلاج العدوى الفطرية الجلدية - ميكونازول',
        'price': '25.00',
        'stock': 80,
        'barcode': '6221060009043',
        'requires_prescription': False,
        'manufacturer': 'جانسن',
        'expiry_date': '2028-02-28',
    },
    {
        'name': 'Dermatin Cream',
        'category': 'أدوية جلدية',
        'description': 'كريم مضاد للفطريات الجلدية - كلوتريمازول',
        'price': '12.00',
        'stock': 95,
        'barcode': '6221060009050',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-09-14',
    },

    # ==========================================
    # 10. أدوية العيون
    # ==========================================
    {
        'name': 'Tobradex Eye Drops',
        'category': 'أدوية العيون',
        'description': 'قطرة عين مضاد حيوي ومضاد للالتهاب - توبراميسين وديكساميثازون',
        'price': '54.00',
        'stock': 45,
        'barcode': '6221060010018',
        'requires_prescription': True,
        'manufacturer': 'ألكون',
        'expiry_date': '2027-06-20',
    },
    {
        'name': 'Tears Naturale',
        'category': 'أدوية العيون',
        'description': 'قطرة مرطبة للعين لعلاج جفاف العين',
        'price': '48.00',
        'stock': 70,
        'barcode': '6221060010025',
        'requires_prescription': False,
        'manufacturer': 'ألكون',
        'expiry_date': '2027-11-30',
    },
    {
        'name': 'Vigamox Eye Drops',
        'category': 'أدوية العيون',
        'description': 'قطرة عين مضاد حيوي لعلاج عدوى العين - موكسيفلوكساسين',
        'price': '60.00',
        'stock': 35,
        'barcode': '6221060010032',
        'requires_prescription': True,
        'manufacturer': 'ألكون',
        'expiry_date': '2028-03-15',
    },
    {
        'name': 'Optipred Eye Drops',
        'category': 'أدوية العيون',
        'description': 'قطرة عين مضادة للالتهاب تحتوي على بريدنيزولون',
        'price': '18.00',
        'stock': 50,
        'barcode': '6221060010049',
        'requires_prescription': True,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-08-22',
    },

    # ==========================================
    # 11. أدوية الحساسية
    # ==========================================
    {
        'name': 'Telfast 180',
        'category': 'أدوية الحساسية',
        'description': 'مضاد للحساسية لا يسبب النعاس - فيكسوفينادين',
        'price': '54.00',
        'stock': 75,
        'barcode': '6221060011015',
        'requires_prescription': False,
        'manufacturer': 'سانوفي',
        'expiry_date': '2028-04-05',
    },
    {
        'name': 'Zyrtec 10',
        'category': 'أدوية الحساسية',
        'description': 'مضاد للحساسية يحتوي على سيتيريزين',
        'price': '36.00',
        'stock': 90,
        'barcode': '6221060011022',
        'requires_prescription': False,
        'manufacturer': 'يو سي بي',
        'expiry_date': '2027-10-18',
    },
    {
        'name': 'Claritine 10',
        'category': 'أدوية الحساسية',
        'description': 'مضاد للحساسية لا يسبب النعاس - لوراتادين',
        'price': '42.00',
        'stock': 80,
        'barcode': '6221060011039',
        'requires_prescription': False,
        'manufacturer': 'باير',
        'expiry_date': '2028-01-22',
    },
    {
        'name': 'Aerius 5',
        'category': 'أدوية الحساسية',
        'description': 'مضاد للحساسية من الجيل الثالث - ديسلوراتادين',
        'price': '60.00',
        'stock': 55,
        'barcode': '6221060011046',
        'requires_prescription': False,
        'manufacturer': 'باير',
        'expiry_date': '2027-09-05',
    },
    {
        'name': 'Avamys Nasal Spray',
        'category': 'أدوية الحساسية',
        'description': 'بخاخ أنف لعلاج حساسية الأنف - فلوتيكازون فيورات',
        'price': '95.00',
        'stock': 40,
        'barcode': '6221060011053',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-12-15',
    },
    {
        'name': 'Fenistil Drops',
        'category': 'أدوية الحساسية',
        'description': 'نقط مضادة للحساسية للأطفال والكبار - ديميتيندين',
        'price': '30.00',
        'stock': 65,
        'barcode': '6221060011060',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2028-02-08',
    },

    # ==========================================
    # 12. أدوية الجهاز التنفسي
    # ==========================================
    {
        'name': 'Ventolin Inhaler',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'بخاخ موسع للشعب الهوائية لعلاج الربو وضيق التنفس - سالبيوتامول',
        'price': '30.00',
        'stock': 55,
        'barcode': '6221060012012',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-07-10',
    },
    {
        'name': 'Symbicort Turbuhaler',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'بخاخ لعلاج الربو والانسداد الرئوي المزمن - بوديسونيد وفورموتيرول',
        'price': '250.00',
        'stock': 25,
        'barcode': '6221060012029',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2027-11-20',
    },
    {
        'name': 'Singulair 10',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'يستخدم لعلاج الربو والحساسية الصدرية - مونتيلوكاست',
        'price': '78.00',
        'stock': 50,
        'barcode': '6221060012036',
        'requires_prescription': True,
        'manufacturer': 'ميرك شارب آند دوم',
        'expiry_date': '2028-03-25',
    },
    {
        'name': 'Sinecod Syrup',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'شراب مهدئ للسعال الجاف - بيوتاميرات',
        'price': '24.00',
        'stock': 80,
        'barcode': '6221060012043',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-06-28',
    },
    {
        'name': 'Mucinex 600',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'يستخدم لإذابة البلغم وعلاج الكحة المصحوبة ببلغم - جوايفينيسين',
        'price': '45.00',
        'stock': 60,
        'barcode': '6221060012050',
        'requires_prescription': False,
        'manufacturer': 'ريكيت بنكيزر',
        'expiry_date': '2028-05-12',
    },

    # ==========================================
    # 13. أدوية المفاصل والعظام
    # ==========================================
    {
        'name': 'Celebrex 200',
        'category': 'أدوية المفاصل والعظام',
        'description': 'مسكن ومضاد للالتهابات لعلاج التهاب المفاصل - سيليكوكسيب',
        'price': '72.00',
        'stock': 50,
        'barcode': '6221060013019',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2027-09-30',
    },
    {
        'name': 'Myolgin',
        'category': 'أدوية المفاصل والعظام',
        'description': 'مسكن وباسط للعضلات لعلاج تشنجات وآلام العضلات',
        'price': '24.00',
        'stock': 85,
        'barcode': '6221060013026',
        'requires_prescription': False,
        'manufacturer': 'آمون للأدوية',
        'expiry_date': '2028-01-18',
    },
    {
        'name': 'Relaxon',
        'category': 'أدوية المفاصل والعظام',
        'description': 'باسط للعضلات ومسكن لآلام العضلات والمفاصل',
        'price': '27.00',
        'stock': 75,
        'barcode': '6221060013033',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-08-15',
    },
    {
        'name': 'Alphintern',
        'category': 'أدوية المفاصل والعظام',
        'description': 'مضاد للالتهاب والتورم - كيموتريبسين وتريبسين',
        'price': '36.00',
        'stock': 65,
        'barcode': '6221060013040',
        'requires_prescription': False,
        'manufacturer': 'آمون للأدوية',
        'expiry_date': '2028-04-08',
    },
    {
        'name': 'Glucosamine 1500',
        'category': 'أدوية المفاصل والعظام',
        'description': 'مكمل غذائي لتقوية المفاصل والغضاريف - جلوكوزامين',
        'price': '90.00',
        'stock': 40,
        'barcode': '6221060013057',
        'requires_prescription': False,
        'manufacturer': 'إيفا فارما',
        'expiry_date': '2027-12-05',
    },

    # ==========================================
    # 14. أدوية الأعصاب والنفسية
    # ==========================================
    {
        'name': 'Cipralex 10',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'مضاد للاكتئاب والقلق يحتوي على إسيتالوبرام',
        'price': '120.00',
        'stock': 35,
        'barcode': '6221060014016',
        'requires_prescription': True,
        'manufacturer': 'لوندبيك',
        'expiry_date': '2027-10-12',
    },
    {
        'name': 'Dogmatil 50',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'يستخدم لعلاج القلق والاضطرابات النفسية - سولبيريد',
        'price': '30.00',
        'stock': 45,
        'barcode': '6221060014023',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2028-02-15',
    },
    {
        'name': 'Tegretol 200',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'يستخدم لعلاج الصرع والتشنجات وآلام الأعصاب - كاربامازيبين',
        'price': '36.00',
        'stock': 40,
        'barcode': '6221060014030',
        'requires_prescription': True,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-07-28',
    },
    {
        'name': 'Lyrica 150',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'يستخدم لعلاج آلام الأعصاب والصرع - بريجابالين',
        'price': '108.00',
        'stock': 30,
        'barcode': '6221060014047',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-05-20',
    },
    {
        'name': 'Trileptal 300',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'يستخدم لعلاج الصرع - أوكسكاربازيبين',
        'price': '96.00',
        'stock': 25,
        'barcode': '6221060014054',
        'requires_prescription': True,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2027-11-08',
    },
    {
        'name': 'Neurobion Forte',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'مكمل غذائي لتقوية الأعصاب يحتوي على فيتامينات ب1 وب6 وب12',
        'price': '42.00',
        'stock': 80,
        'barcode': '6221060014061',
        'requires_prescription': False,
        'manufacturer': 'ميرك',
        'expiry_date': '2028-03-30',
    },

    # ==========================================
    # 15. أدوية الأطفال
    # ==========================================
    {
        'name': 'Calpol Syrup',
        'category': 'أدوية الأطفال',
        'description': 'شراب خافض للحرارة ومسكن للأطفال - باراسيتامول',
        'price': '18.00',
        'stock': 120,
        'barcode': '6221060015013',
        'requires_prescription': False,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-06-10',
    },
    {
        'name': 'Flagyl Syrup',
        'category': 'أدوية الأطفال',
        'description': 'شراب مضاد للبكتيريا والطفيليات للأطفال - ميترونيدازول',
        'price': '12.00',
        'stock': 90,
        'barcode': '6221060015020',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2027-10-25',
    },
    {
        'name': 'Amoxil Syrup 250',
        'category': 'أدوية الأطفال',
        'description': 'شراب مضاد حيوي للأطفال - أموكسيسيلين',
        'price': '24.00',
        'stock': 80,
        'barcode': '6221060015037',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2028-01-08',
    },
    {
        'name': 'Prospan Syrup',
        'category': 'أدوية الأطفال',
        'description': 'شراب طبيعي لعلاج الكحة وطارد للبلغم للأطفال - خلاصة أوراق اللبلاب',
        'price': '48.00',
        'stock': 100,
        'barcode': '6221060015044',
        'requires_prescription': False,
        'manufacturer': 'إنجلهارد',
        'expiry_date': '2027-08-18',
    },
    {
        'name': 'Pedialyte Solution',
        'category': 'أدوية الأطفال',
        'description': 'محلول معالجة الجفاف للأطفال يحتوي على أملاح وسكريات',
        'price': '15.00',
        'stock': 110,
        'barcode': '6221060015051',
        'requires_prescription': False,
        'manufacturer': 'أبوت',
        'expiry_date': '2028-04-30',
    },
    {
        'name': 'Baby Rexal Drops',
        'category': 'أدوية الأطفال',
        'description': 'نقط خافضة للحرارة ومسكنة للأطفال الرضع - باراسيتامول',
        'price': '10.00',
        'stock': 130,
        'barcode': '6221060015068',
        'requires_prescription': False,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-05-20',
    },
    {
        'name': 'Dentinox Gel',
        'category': 'أدوية الأطفال',
        'description': 'جل لتخفيف آلام التسنين عند الأطفال',
        'price': '35.00',
        'stock': 70,
        'barcode': '6221060015075',
        'requires_prescription': False,
        'manufacturer': 'دنتينوكس',
        'expiry_date': '2028-02-22',
    },

    # ==========================================
    # Additional medicines to reach 80+
    # ==========================================
    {
        'name': 'Norvasc 5',
        'category': 'أدوية الضغط',
        'description': 'يستخدم لعلاج ارتفاع ضغط الدم والذبحة الصدرية - أملوديبين',
        'price': '54.00',
        'stock': 55,
        'barcode': '6221060005076',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2028-06-10',
    },
    {
        'name': 'Predsol Eye Drops',
        'category': 'أدوية العيون',
        'description': 'قطرة عين مضادة للالتهاب - بريدنيزولون',
        'price': '15.00',
        'stock': 60,
        'barcode': '6221060010056',
        'requires_prescription': True,
        'manufacturer': 'الشركة المصرية الدولية للصناعات الدوائية (ايبيكو)',
        'expiry_date': '2027-09-28',
    },
    {
        'name': 'Brufen Syrup',
        'category': 'أدوية الأطفال',
        'description': 'شراب مسكن وخافض للحرارة للأطفال - ايبوبروفين',
        'price': '21.00',
        'stock': 85,
        'barcode': '6221060015082',
        'requires_prescription': False,
        'manufacturer': 'أبوت',
        'expiry_date': '2027-12-18',
    },
    {
        'name': 'Voltaren Gel',
        'category': 'أدوية المفاصل والعظام',
        'description': 'جل موضعي مسكن ومضاد للالتهابات - ديكلوفيناك',
        'price': '36.00',
        'stock': 90,
        'barcode': '6221060013064',
        'requires_prescription': False,
        'manufacturer': 'نوفارتس',
        'expiry_date': '2028-05-05',
    },
    {
        'name': 'Ventolin Nebules',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'محلول استنشاق لعلاج أزمات الربو - سالبيوتامول',
        'price': '22.00',
        'stock': 65,
        'barcode': '6221060012067',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-08-12',
    },
    {
        'name': 'Glucophage 500',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج مرض السكر من النوع الثاني - ميتفورمين 500 مجم',
        'price': '15.00',
        'stock': 100,
        'barcode': '6221060004075',
        'requires_prescription': True,
        'manufacturer': 'ميرك',
        'expiry_date': '2028-04-22',
    },
    {
        'name': 'Daktacort Cream',
        'category': 'أدوية جلدية',
        'description': 'كريم مضاد للفطريات والالتهابات الجلدية - ميكونازول وهيدروكورتيزون',
        'price': '30.00',
        'stock': 55,
        'barcode': '6221060009067',
        'requires_prescription': False,
        'manufacturer': 'جانسن',
        'expiry_date': '2027-11-28',
    },
    {
        'name': 'Augmentin Syrup 457',
        'category': 'أدوية الأطفال',
        'description': 'شراب مضاد حيوي للأطفال - أموكسيسيلين وحمض كلافولانيك',
        'price': '72.00',
        'stock': 50,
        'barcode': '6221060015099',
        'requires_prescription': True,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-07-05',
    },
    {
        'name': 'Nexium Sachets 10',
        'category': 'أدوية الجهاز الهضمي',
        'description': 'أكياس لعلاج الحموضة وارتجاع المريء - إيزوميبرازول',
        'price': '60.00',
        'stock': 45,
        'barcode': '6221060007087',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2028-01-30',
    },
    {
        'name': 'Crestor 10',
        'category': 'أدوية القلب والأوعية الدموية',
        'description': 'يستخدم لخفض الكوليسترول والدهون الثلاثية - روزوفاستاتين',
        'price': '105.00',
        'stock': 40,
        'barcode': '6221060003061',
        'requires_prescription': True,
        'manufacturer': 'أسترازينيكا',
        'expiry_date': '2028-06-01',
    },
    {
        'name': 'Xanax 0.5',
        'category': 'أدوية الأعصاب والنفسية',
        'description': 'يستخدم لعلاج القلق والتوتر والأرق - ألبرازولام',
        'price': '36.00',
        'stock': 20,
        'barcode': '6221060014078',
        'requires_prescription': True,
        'manufacturer': 'فايزر',
        'expiry_date': '2027-10-30',
    },
    {
        'name': 'Bisolvon Syrup',
        'category': 'أدوية الجهاز التنفسي',
        'description': 'شراب مذيب للبلغم ومهدئ للكحة - برومهيكسين',
        'price': '18.00',
        'stock': 90,
        'barcode': '6221060012074',
        'requires_prescription': False,
        'manufacturer': 'بورنغر إنغلهايم',
        'expiry_date': '2027-12-22',
    },
    {
        'name': 'Janumet 50/1000',
        'category': 'أدوية السكر',
        'description': 'يستخدم لعلاج السكر النوع الثاني - سيتاجليبتين وميتفورمين',
        'price': '240.00',
        'stock': 30,
        'barcode': '6221060004082',
        'requires_prescription': True,
        'manufacturer': 'ميرك شارب آند دوم',
        'expiry_date': '2028-03-18',
    },
    {
        'name': 'Pandol Night',
        'category': 'مسكنات وخوافض حرارة',
        'description': 'مسكن للآلام ومساعد على النوم - باراسيتامول وديفينهيدرامين',
        'price': '30.00',
        'stock': 70,
        'barcode': '6221060001081',
        'requires_prescription': False,
        'manufacturer': 'جلاكسو سميث كلاين',
        'expiry_date': '2027-11-10',
    },
    {
        'name': 'Tarivid 200',
        'category': 'مضادات حيوية',
        'description': 'مضاد حيوي من مجموعة الفلوروكينولون - أوفلوكساسين',
        'price': '48.00',
        'stock': 35,
        'barcode': '6221060002095',
        'requires_prescription': True,
        'manufacturer': 'سانوفي',
        'expiry_date': '2028-02-05',
    },
]
