# Generated by Django 6.0.3 on 2026-03-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_product_options_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=300, verbose_name='اسم المريض')),
                ('patient_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم تليفون المريض')),
                ('doctor_name', models.CharField(blank=True, max_length=300, verbose_name='اسم الدكتور')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/', verbose_name='صورة الروشتة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'روشتة',
                'verbose_name_plural': 'الروشتات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('dosage', models.CharField(blank=True, help_text='مثال: قرص كل 8 ساعات', max_length=300, verbose_name='الجرعة')),
                ('duration', models.CharField(blank=True, help_text='مثال: 7 أيام', max_length=200, verbose_name='المدة')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription', verbose_name='الروشتة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='pharmacy.product', verbose_name='الدواء')),
            ],
            options={
                'verbose_name': 'عنصر روشتة',
                'verbose_name_plural': 'عناصر الروشتة',
            },
        ),
    ]
